---
output:
  html_document:
    keep_md: true
---


```{r options, echo = F}
opts_chunk$set(dev = "png", dev.args = list(type = "cairo"), dpi = 192, fig.path = "figures/", comment = NA, results = 'markup', tidy = F, message = F, warning = F, echo = T)
```

```{r inc, echo = F}
library(devtools)
load_all("~/git/variani/finemapr")
```

```{r ex}
# specify path to PAINTOR (user-specific)
options(finemapr_paintor = "~/apps/paintor/PAINTOR")

# load the same example data as for FINEMAP
ex <- example_finemap()

# run the tool
# - arg. #1: table with SNP name and Z-score in the first 2 columns
# - arg. #2: the LD matrix with colnames/rownames corresponding to SNP names
# - arg. #3 (optional; the default value is 1,000,000): the number of invidivudals
# - arg. `args`: pass other arguments to the tool as a string 
out_paintor <- run_paintor(ex$tab1, ex$ld1, ex$n1, args = "-enumerate 3")
```

```{r print}
print(out_paintor)
```

```{r plot_paintor, fig.width = 6, fig.height = 3}
plot(out_paintor, label_size = 3)
```

